"""Compatibility export surface for Peewee ORM models."""

from __future__ import annotations

from app.db._models_aggregation import AggregationSession, AggregationSessionItem
from app.db._models_base import (
    TOPIC_SEARCH_INDEX_OPTIONS,
    BaseModel,
    _next_server_version,
    _utcnow,
    database_proxy,
    model_to_dict,
)
from app.db._models_batch import BatchSession, BatchSessionItem
from app.db._models_collections import (
    Collection,
    CollectionCollaborator,
    CollectionInvite,
    CollectionItem,
)
from app.db._models_core import (
    AttachmentProcessing,
    AudioGeneration,
    AuditLog,
    Chat,
    ClientSecret,
    CrawlResult,
    LLMCall,
    RefreshToken,
    Request,
    Summary,
    SummaryEmbedding,
    TelegramMessage,
    TopicSearchIndex,
    User,
    UserDevice,
    UserInteraction,
    VideoDownload,
)
from app.db._models_digest import (
    Channel,
    ChannelCategory,
    ChannelPost,
    ChannelPostAnalysis,
    ChannelSubscription,
    DigestDelivery,
    UserDigestPreference,
)
from app.db._models_rss import RSSFeed, RSSFeedItem, RSSFeedSubscription, RSSItemDelivery
from app.db._models_rules import (
    AutomationRule,
    ImportJob,
    RuleExecutionLog,
    UserBackup,
    WebhookDelivery,
    WebhookSubscription,
)
from app.db._models_signal import FeedItem, Source, Subscription, Topic, UserSignal
from app.db._models_user_content import (
    CustomDigest,
    SummaryFeedback,
    SummaryHighlight,
    SummaryTag,
    Tag,
    UserGoal,
)

__all__ = [
    "ALL_MODELS",
    "TOPIC_SEARCH_INDEX_OPTIONS",
    "AggregationSession",
    "AggregationSessionItem",
    "AttachmentProcessing",
    "AudioGeneration",
    "AuditLog",
    "AutomationRule",
    "BaseModel",
    "BatchSession",
    "BatchSessionItem",
    "Channel",
    "ChannelCategory",
    "ChannelPost",
    "ChannelPostAnalysis",
    "ChannelSubscription",
    "Chat",
    "ClientSecret",
    "Collection",
    "CollectionCollaborator",
    "CollectionInvite",
    "CollectionItem",
    "CrawlResult",
    "CustomDigest",
    "DigestDelivery",
    "FeedItem",
    "ImportJob",
    "LLMCall",
    "RSSFeed",
    "RSSFeedItem",
    "RSSFeedSubscription",
    "RSSItemDelivery",
    "RefreshToken",
    "Request",
    "RuleExecutionLog",
    "Source",
    "Subscription",
    "Summary",
    "SummaryEmbedding",
    "SummaryFeedback",
    "SummaryHighlight",
    "SummaryTag",
    "Tag",
    "TelegramMessage",
    "Topic",
    "TopicSearchIndex",
    "User",
    "UserBackup",
    "UserDevice",
    "UserDigestPreference",
    "UserGoal",
    "UserInteraction",
    "UserSignal",
    "VideoDownload",
    "WebhookDelivery",
    "WebhookSubscription",
    "_next_server_version",
    "_utcnow",
    "database_proxy",
    "model_to_dict",
]

ALL_MODELS = (
    User,
    Chat,
    Request,
    AggregationSession,
    AggregationSessionItem,
    TelegramMessage,
    CrawlResult,
    LLMCall,
    Summary,
    TopicSearchIndex,
    UserInteraction,
    AuditLog,
    SummaryEmbedding,
    VideoDownload,
    AudioGeneration,
    AttachmentProcessing,
    ClientSecret,
    Collection,
    CollectionItem,
    CollectionCollaborator,
    CollectionInvite,
    UserDevice,
    RefreshToken,
    BatchSession,
    BatchSessionItem,
    Channel,
    ChannelCategory,
    ChannelSubscription,
    ChannelPost,
    ChannelPostAnalysis,
    DigestDelivery,
    UserDigestPreference,
    SummaryFeedback,
    CustomDigest,
    SummaryHighlight,
    UserGoal,
    Tag,
    SummaryTag,
    WebhookSubscription,
    WebhookDelivery,
    AutomationRule,
    RuleExecutionLog,
    ImportJob,
    UserBackup,
    RSSFeed,
    RSSFeedSubscription,
    RSSFeedItem,
    RSSItemDelivery,
    Source,
    Subscription,
    FeedItem,
    Topic,
    UserSignal,
)
