# markdownlint-cli2 configuration
# Documentation: https://github.com/DavidAnson/markdownlint-cli2

config:
  # MD013: Line length - disabled for documentation flexibility
  MD013: false

  # MD033: Allow inline HTML (needed for Mermaid diagrams, tables, etc.)
  MD033: false

  # MD041: First line in file should be top-level heading - disabled for files with YAML frontmatter
  MD041: false

  # MD046: Code block style - allow both fenced and indented
  MD046:
    style: "consistent"

  # MD024: Allow duplicate headings (common in documentation with multiple "Examples" sections)
  MD024:
    siblings_only: true

  # MD025: Multiple top-level headings - allow for README files
  MD025: false

  # MD026: Trailing punctuation in heading - allow for questions in headings
  MD026:
    punctuation: ".,;:"

  # MD034: Bare URL used - allow for reference sections
  MD034: false

  # MD040: Fenced code blocks should have a language specified
  # Disabled to allow code blocks without language (common in documentation examples)
  MD040: false

  # MD036: Emphasis used instead of a heading - allow for emphasized text in lists
  MD036: false

  # MD051: Link fragments should be valid - disabled due to non-breaking hyphens in SPEC.md headings
  MD051: false

  # MD012: Multiple consecutive blank lines
  MD012:
    maximum: 2

  # MD022: Headings should be surrounded by blank lines
  MD022:
    lines_above: 1
    lines_below: 1

# Files to ignore
ignores:
  - "node_modules/**"
  - ".venv/**"
  - "venv/**"
  - "build/**"
  - "dist/**"
  - "*.md.bak"
  - "CHANGELOG.md"  # Auto-generated, different format
