"""Example: Phase 3 Orchestrator Features.

This demonstrates the advanced orchestration features added in Phase 3:
1. Parallel batch processing for multiple URLs
2. Streaming pipeline with progress updates
3. Advanced retry strategies with configurable backoff
4. Pipeline state persistence for resuming interrupted workflows

Phase 3 Achievements:
✅ Batch processing with concurrency control
✅ Streaming progress updates
✅ Exponential/linear/fixed retry strategies
✅ State persistence and resumption
"""

import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

print("=== Phase 3 Orchestrator Features Example ===\n")
print("📋 This example demonstrates the API structure for Phase 3 features\n")

# Example 1: Parallel Batch Processing
print("1️⃣  Parallel Batch Processing")
print("=" * 60)
print()
print("Process multiple URLs concurrently with semaphore limiting:")
print()
print("```python")
print("from app.agents.orchestrator import (")
print("    AgentOrchestrator, BatchPipelineInput, RetryConfig, RetryStrategy")
print(")")
print()
print("# Initialize orchestrator")
print("orchestrator = AgentOrchestrator(")
print("    extraction_agent, summarization_agent, validation_agent")
print(")")
print()
print("# Batch process multiple URLs")
print("batch_input = BatchPipelineInput(")
print("    urls=[")
print('        "https://example.com/article1",')
print('        "https://example.com/article2",')
print('        "https://example.com/article3",')
print("    ],")
print('    base_correlation_id="batch-123",')
print('    language="en",')
print("    max_concurrent=3,  # Process 3 URLs at a time")
print("    retry_config=RetryConfig(")
print("        strategy=RetryStrategy.EXPONENTIAL,")
print("        max_attempts=3,")
print("        initial_delay_ms=1000,")
print("        backoff_multiplier=2.0")
print("    )")
print(")")
print()
print("# Execute batch")
print("results = await orchestrator.execute_batch_pipeline(batch_input)")
print()
print("# Results is a list of BatchPipelineOutput objects")
print("for result in results:")
print("    if result.success:")
print('        print(f"✅ {result.url}: Success")')
print("    else:")
print('        print(f"❌ {result.url}: {result.error}")')
print("```")
print()
print("Key Features:")
print("  • Semaphore-based concurrency limiting")
print("  • Parallel processing of multiple URLs")
print("  • Individual error handling per URL")
print("  • Batch summary logging")
print()

# Example 2: Streaming Pipeline
print("2️⃣  Streaming Pipeline with Progress Updates")
print("=" * 60)
print()
print("Stream progress updates for long-running operations:")
print()
print("```python")
print("from app.agents.orchestrator import (")
print("    AgentOrchestrator, PipelineInput, PipelineProgress")
print(")")
print()
print("# Initialize orchestrator")
print("orchestrator = AgentOrchestrator(")
print("    extraction_agent, summarization_agent, validation_agent")
print(")")
print()
print("# Execute with streaming")
print("pipeline_input = PipelineInput(")
print('    url="https://example.com/article",')
print('    correlation_id="stream-123",')
print('    language="en"')
print(")")
print()
print("# Async iterator yields progress updates, then final result")
print("async for update in orchestrator.execute_pipeline_streaming(pipeline_input):")
print("    if isinstance(update, PipelineProgress):")
print("        # Progress update")
print('        print(f"[{update.progress_percent}%] {update.stage.value}: {update.message}")')
print("    else:")
print("        # Final result")
print("        if update['success']:")
print('            print("✅ Pipeline complete!")')
print("            output = update['output']")
print('            print(f"   Summary attempts: {output.summarization_attempts}")')
print("```")
print()
print("Progress Updates:")
print("  • Stage: EXTRACTION (10-40%)")
print("  • Stage: SUMMARIZATION (50-90%)")
print("  • Stage: COMPLETE (100%)")
print("  • Metadata: content_length, attempts, corrections")
print()

# Example 3: Advanced Retry Strategies
print("3️⃣  Advanced Retry Strategies")
print("=" * 60)
print()
print("Configure retry behavior with different strategies:")
print()
print("```python")
print("from app.agents.orchestrator import RetryConfig, RetryStrategy, PipelineInput")
print()
print("# Exponential backoff (default)")
print("exponential_retry = RetryConfig(")
print("    strategy=RetryStrategy.EXPONENTIAL,")
print("    max_attempts=5,")
print("    initial_delay_ms=1000,  # 1s")
print("    max_delay_ms=30000,     # 30s cap")
print("    backoff_multiplier=2.0  # 1s -> 2s -> 4s -> 8s -> 16s")
print(")")
print()
print("# Linear backoff")
print("linear_retry = RetryConfig(")
print("    strategy=RetryStrategy.LINEAR,")
print("    max_attempts=3,")
print("    initial_delay_ms=2000   # 2s -> 4s -> 6s")
print(")")
print()
print("# Fixed delay")
print("fixed_retry = RetryConfig(")
print("    strategy=RetryStrategy.FIXED,")
print("    max_attempts=3,")
print("    initial_delay_ms=5000   # 5s every time")
print(")")
print()
print("# Use in pipeline")
print("pipeline_input = PipelineInput(")
print('    url="https://example.com/article",')
print('    correlation_id="retry-123",')
print("    retry_config=exponential_retry")
print(")")
print("```")
print()
print("Retry Strategies:")
print("  • EXPONENTIAL: 1s → 2s → 4s → 8s → 16s (with multiplier 2.0)")
print("  • LINEAR: 1s → 2s → 3s → 4s → 5s")
print("  • FIXED: 5s → 5s → 5s → 5s → 5s")
print("  • NONE: No delays between attempts")
print()

# Example 4: State Persistence
print("4️⃣  Pipeline State Persistence")
print("=" * 60)
print()
print("Save/resume pipeline state for long-running operations:")
print()
print("```python")
print("from pathlib import Path")
print("from app.agents.orchestrator import PipelineInput")
print()
print('state_dir = Path("/tmp/pipeline_states")')
print()
print("# Enable state persistence")
print("pipeline_input = PipelineInput(")
print('    url="https://example.com/long-article",')
print('    correlation_id="persist-123",')
print('    language="en",')
print("    enable_state_persistence=True,")
print("    state_dir=state_dir")
print(")")
print()
print("# Execute pipeline (saves state after each stage)")
print("try:")
print("    result = await orchestrator.execute_pipeline(pipeline_input)")
print("except Exception as e:")
print('    print(f"Pipeline interrupted: {e}")')
print('    print("State saved - can resume later")')
print()
print("# Resume from saved state")
print("# (same correlation_id will load and continue from last stage)")
print("result = await orchestrator.execute_pipeline(pipeline_input)")
print("```")
print()
print("State Management:")
print("  • Saves after extraction stage")
print("  • Saves after summarization stage")
print("  • Resumes from last completed stage")
print("  • Cleans up state file on completion")
print("  • State files: /tmp/pipeline_states/<correlation_id>.json")
print()

# Example 5: Combined Features
print("5️⃣  Combined Features Example")
print("=" * 60)
print()
print("Use multiple Phase 3 features together:")
print()
print("```python")
print("# Batch processing with retry + streaming progress")
print("import asyncio")
print("from app.agents.orchestrator import (")
print("    AgentOrchestrator, BatchPipelineInput, RetryConfig, RetryStrategy")
print(")")
print()
print("async def process_articles_with_retry():")
print("    # Setup")
print("    orchestrator = AgentOrchestrator(...)")
print("    ")
print("    urls = [")
print('        "https://news.site/article1",')
print('        "https://news.site/article2",')
print('        "https://news.site/article3",')
print("    ]")
print("    ")
print("    # Batch with exponential retry")
print("    batch_input = BatchPipelineInput(")
print("        urls=urls,")
print('        base_correlation_id="news-batch",')
print("        max_concurrent=2,")
print("        retry_config=RetryConfig(")
print("            strategy=RetryStrategy.EXPONENTIAL,")
print("            max_attempts=3,")
print("            initial_delay_ms=1000")
print("        )")
print("    )")
print("    ")
print("    # Execute")
print("    results = await orchestrator.execute_batch_pipeline(batch_input)")
print("    ")
print("    # Process results")
print("    successful = [r for r in results if r.success]")
print('    print(f"Processed {len(successful)}/{len(results)} articles")')
print("    ")
print("    return successful")
print()
print("# Run")
print("results = asyncio.run(process_articles_with_retry())")
print("```")
print()

# Summary
print("📊 Phase 3 Summary")
print("=" * 60)
print()
print("Comparison Across Phases:")
print()
print("Phase 1:")
print("  ✅ ValidationAgent - Fully functional")
print()
print("Phase 2:")
print("  ✅ ContentExtractionAgent - Message-independent extraction")
print("  ✅ SummarizationAgent - Message-independent summarization")
print("  ✅ Complete pipeline without Telegram dependencies")
print()
print("Phase 3:")
print("  ✅ Parallel batch processing (execute_batch_pipeline)")
print("  ✅ Streaming progress updates (execute_pipeline_streaming)")
print("  ✅ Advanced retry strategies (RetryConfig + RetryStrategy)")
print("  ✅ Pipeline state persistence (PipelineState)")
print()
print("Use Cases:")
print("  • Batch: Process RSS feeds, scrape multiple pages")
print("  • Streaming: Long articles with progress bars")
print("  • Retry: Handle flaky API calls with backoff")
print("  • Persistence: Resume interrupted batch jobs")
print()
print("Next Steps:")
print("  1. See docs/multi_agent_architecture.md for detailed API docs")
print("  2. Check app/agents/orchestrator.py for implementation")
print("  3. Review examples/agent_pipeline_example.py for Phase 2 basics")
print()
print("=== Example Complete ===")
