# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: processing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import (
    descriptor as _descriptor,
    descriptor_pool as _descriptor_pool,
    runtime_version as _runtime_version,
    symbol_database as _symbol_database,
)
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "processing.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10processing.proto\x12\rprocessing.v1"H\n\x10SubmitUrlRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x15\n\rforce_refresh\x18\x03 \x01(\x08"\xcc\x01\n\x10ProcessingUpdate\x12\x12\n\nrequest_id\x18\x01 \x01(\x03\x12/\n\x06status\x18\x02 \x01(\x0e\x32\x1f.processing.v1.ProcessingStatus\x12-\n\x05stage\x18\x03 \x01(\x0e\x32\x1e.processing.v1.ProcessingStage\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x10\n\x08progress\x18\x05 \x01(\x02\x12\x12\n\nsummary_id\x18\x06 \x01(\x03\x12\r\n\x05\x65rror\x18\x07 \x01(\t*\xb0\x01\n\x10ProcessingStatus\x12 \n\x1cProcessingStatus_UNSPECIFIED\x10\x00\x12\x1c\n\x18ProcessingStatus_PENDING\x10\x01\x12\x1f\n\x1bProcessingStatus_PROCESSING\x10\x02\x12\x1e\n\x1aProcessingStatus_COMPLETED\x10\x03\x12\x1b\n\x17ProcessingStatus_FAILED\x10\x04*\xc7\x01\n\x0fProcessingStage\x12\x1f\n\x1bProcessingStage_UNSPECIFIED\x10\x00\x12\x1a\n\x16ProcessingStage_QUEUED\x10\x01\x12\x1e\n\x1aProcessingStage_EXTRACTION\x10\x02\x12!\n\x1dProcessingStage_SUMMARIZATION\x10\x03\x12\x1a\n\x16ProcessingStage_SAVING\x10\x04\x12\x18\n\x14ProcessingStage_DONE\x10\x05\x32\x64\n\x11ProcessingService\x12O\n\tSubmitUrl\x12\x1f.processing.v1.SubmitUrlRequest\x1a\x1f.processing.v1.ProcessingUpdate0\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "processing_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PROCESSINGSTATUS"]._serialized_start = 317
    _globals["_PROCESSINGSTATUS"]._serialized_end = 493
    _globals["_PROCESSINGSTAGE"]._serialized_start = 496
    _globals["_PROCESSINGSTAGE"]._serialized_end = 695
    _globals["_SUBMITURLREQUEST"]._serialized_start = 35
    _globals["_SUBMITURLREQUEST"]._serialized_end = 107
    _globals["_PROCESSINGUPDATE"]._serialized_start = 110
    _globals["_PROCESSINGUPDATE"]._serialized_end = 314
    _globals["_PROCESSINGSERVICE"]._serialized_start = 697
    _globals["_PROCESSINGSERVICE"]._serialized_end = 797
# @@protoc_insertion_point(module_scope)
