# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import processing_pb2 as processing__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        " but the generated code in processing_pb2_grpc.py depends on"
        f" grpcio>={GRPC_GENERATED_VERSION}."
        f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ProcessingServiceStub:
    """Service definition"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitUrl = channel.unary_stream(
            "/processing.v1.ProcessingService/SubmitUrl",
            request_serializer=processing__pb2.SubmitUrlRequest.SerializeToString,
            response_deserializer=processing__pb2.ProcessingUpdate.FromString,
            _registered_method=True,
        )


class ProcessingServiceServicer:
    """Service definition"""

    def SubmitUrl(self, request, context):  # noqa: N802
        """Submits a URL for processing and streams back status updates"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ProcessingServiceServicer_to_server(servicer, server):  # noqa: N802
    rpc_method_handlers = {
        "SubmitUrl": grpc.unary_stream_rpc_method_handler(
            servicer.SubmitUrl,
            request_deserializer=processing__pb2.SubmitUrlRequest.FromString,
            response_serializer=processing__pb2.ProcessingUpdate.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "processing.v1.ProcessingService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("processing.v1.ProcessingService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ProcessingService:
    """Service definition"""

    @staticmethod
    def SubmitUrl(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/processing.v1.ProcessingService/SubmitUrl",
            processing__pb2.SubmitUrlRequest.SerializeToString,
            processing__pb2.ProcessingUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
